### ISSUE TITLE
if the message show class JBrowser not found

### ISSUE THREAD

**Issue by alexonbalangue** [alexonbalangue/template-CVStart-Joomla#1]
add and use the legacy code docs on joomla [https://docs.joomla.org/J3.x:Missing_JBrowser_class_after_upgrading](https://docs.joomla.org/J3.x:Missing_JBrowser_class_after_upgrading) works with 3.6.2.

**Comment by Ayushi271** [comment]
Can I fix this issue

**Comment by Ayushi271** [comment]
I have create a PR can you please review it.

**Comment by alexonbalangue** [comment]
ok nice is merge

**Comment by Ayushi271** [comment]
Thanks for merging.
